sudo: false
dist: trusty
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
env:
 - BASE=3.16 STATIC=shared CMPLR=clang WINE=32
 - BASE=3.16 STATIC=shared RTEMS=4.10
 - BASE=3.16 STATIC=static WINE=32
 - BASE=3.15 STATIC=shared
 - BASE=3.14 STATIC=shared
install: ./.ci/travis-prepare.sh
script: make -j2
